language: android
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
